### ISSUE TITLE
Script needed a small edit to work for me

### ISSUE THREAD

**Issue by theopavlakou** [AntreasAntoniou/helpful_scripts#1]
I needed to include 
source /home/s1473470/anaconda2/envs/deeplearning/bin/activate deeplearning

instead of just 

source /home/s1473470/anaconda2/envs/deeplearning/bin/activate

**Comment by AntreasAntoniou** [comment]
I see. Yeah, we did get a similar problem. Where we used source /home/s1473470/anaconda2/envs/deeplearning/bin/activate and it would go into root. We didn't see the issue before since my (root) had the same tools as the deeplearning one. We only caught this later. Thanks I will update

**Comment by AntreasAntoniou** [comment]
Updated scripts! Thanks for the shout out.
